version: '2'
services:
  #transmission - torrent client
  transmission:
    image: linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1001
      - TZ=America/Chicago
      - TRANSMISSION_WEB_HOME=/combustion-release/ #optional
    volumes:
      - /media/server/External/appdata/transmission/config:/config
      - complete_downloads:/downloads
      - watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    mem_limit: 4096m
    restart: unless-stopped
  #couchpotato - tv shows
  couchpotato:
    image: linuxserver/couchpotato
    container_name: couchpotato
    ports:
    - 5050:5050
    volumes:
    - /media/server/External/appdata/couchpotato:/config
    - complete_downloads:/downloads
    - watch:/watch # where transmission watches for torrent files
    - movies:/movies
    environment:
    - PUID=1000
    - PGID=1001
    - TZ=America/Chicago
  #heimdall - gateway, manager
  heimdall:
    image: linuxserver/heimdall
    container_name: heimdall
    volumes:
      - /media/server/External/appdata/heimdall/config:/config
    ports:
      - 80:80
    restart: always
    environment:
      - PUID=1000
      - PGID=1001
  #plex - media server
  plex:
    image: linuxserver/plex
    container_name: plex
    volumes:
      - /media/server/External/appdata/plex:/config
      - tv:/data/tvshows
      - home_movies:/data/homemovies
      - photos:/data/photos
      - movies:/data/movies
      - christmas_movies:/data/christmas
      - kids_movies:/data/kids
      - temp_storage:/transcode
    network_mode: host
    restart: always
    environment:
      - VERSION=public
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/Chicago
  #tautulli - plex stats
  tautulli:
    image: linuxserver/tautulli
    container_name: tautulli
    depends_on:
      - plex
    volumes:
      - /media/server/External/appdata/plexpy:/config
      - /media/server/External/appdata/plex/Library/Application\ Support/Plex\ Media\ Server/Logs:/logs:ro
    ports:
      - 8181:8181
    links:
      - plex
    restart: always
    environment:
      - PUID=1000
      - PGID=1001
      - TZ=America/Chicago
  #sonarr - tv downloader
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    depends_on:
      - transmission
    volumes:
      - /media/server/External/appdata/sonarr:/config
      - tv:/tv
      - complete_downloads:/config/Downloads
    # - /media/server/External/media/tv_import:/tv_import
    ports:
      - 8989:8989
    links:
      - transmission
    restart: always
    environment:
      - PUID=1000
      - PGID=1001
  #jackett - proxy for sonarr
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1001
      - TZ=America/Chicago
      #- RUN_OPTS=<run options here> #optional
    volumes:
      - /media/server/External/appdata/jackett:/config
      - complete_downloads:/downloads
    ports:
      - 9117:9117
    mem_limit: 4096m
    restart: unless-stopped
  #portainer - docker manager
  portainer:
    image: portainer/portainer
    container_name: portainer
    ports:
      - 9000:9000
    volumes:
      - /media/server/External/appdata/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart:
      always
  #watchtower - docker image updater
  watchtower:
    container_name: watchtower
    restart: always
    image: v2tec/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  # command: --schedule "0 0 4 * * *" --cleanup
  #netdata - metrics for apps
  netdata:
    image: netdata/netdata
    ports:
      - 19999:19999
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
  



volumes:
  tv:
    driver_opts:
      type: none
      device: /media/server/External/tv
      o: bind
  home_movies:
    driver_opts:
      type: none
      device: /media/server/External/homemovies
      o: bind
  photos:
    driver_opts:
      type: none
      device: /media/server/External/photos
      o: bind
  movies:
    driver_opts:
      type: none
      device: /media/server/External/movies
      o: bind
  kids_movies:
    driver_opts:
      type: none
      device: /media/server/External/kids
      o: bind
  christmas_movies:
    driver_opts:
      type: none
      device: /media/server/External/christmas
      o: bind
  complete_downloads:
    driver_opts:
      type: none
      device: /media/server/External/complete
      o: bind
  watch:
    driver_opts:
      type: none
      device: /media/server/External/watch
      o: bind
  incomplete_downloads:
    driver_opts:
      type: none
      device: /media/server/External/incomplete
      o: bind
  temp_storage:
    driver_opts:
      type: none
      device: /media/server/External/tmp
      o: bind