version: '2'
services:
  #heimdall - gateway, manager
  heimdall:
    image: linuxserver/heimdall
    container_name: heimdall
    volumes:
      - /media/server/External/appdata/heimdall/config:/config
    ports:
      - 80:80
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
  #sabnzbd - downloader
  sabnzbd:
    image: linuxserver/sabnzbd
    container_name: sabnzbd
    volumes:
    #why does sabnzbd need access to comics?
      - comics:/comics
      - /media/server/External/appdata/sabnzbd/config:/config
      - complete_downloads:/config/Downloads
      - incomplete_downloads:/config/incomplete
    ports:
      - 8080:8080
      - 9090:9090
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/New_York
  #nzbhydra - aggregates indxers
  nzbhydra:
    image: linuxserver/hydra
    container_name: hydra
    volumes:
      - /media/server/External/appdata/hydra/config:/config
      - complete_downloads:/downloads
    ports:
      - 5075:5075
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
  #plex - media server
  plex:
    image: linuxserver/plex
    container_name: plex
    volumes:
      - /media/server/External/appdata/plex:/config
      - tv:/data/tvshows
      - home_movies:/data/homemovies
      - photos:/data/photos
      - movies:/data/movies
      - christmas_movies:/data/christmas
      - kids_movies:/data/kids
      - music:/data/music
      - temp_storage:/transcode
    network_mode: host
    restart: always
    environment:
      - VERSION=public
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/New_York
  #tautulli - plex stats
  tautulli:
    image: linuxserver/tautulli
    container_name: tautulli
    depends_on:
      - plex
    volumes:
      - /media/server/External/appdata/plexpy:/config
      - /media/server/External/appdata/plex/Library/Application\ Support/Plex\ Media\ Server/Logs:/logs:ro
    ports:
      - 8181:8181
    links:
      - plex
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/New_York
  #sonarr - tv downloader
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    depends_on:
      - sabnzbd
    volumes:
      - /media/server/External/appdata/sonarr:/config
      - tv:/tv
      - complete_downloads:/config/Downloads
#       - /media/server/External/media/tv_import:/tv_import
    ports:
      - 8989:8989
    links:
      - sabnzbd
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
  #portainer - docker manager
  portainer:
    image: portainer/portainer
    container_name: portainer
    ports:
      - 9000:9000
    volumes:
      - /media/server/External/appdata/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart:
      always
  #lazylibrarian - book/comic manager
  lazylibrarian:
    image: linuxserver/lazylibrarian
    container_name: lazylibrarian
    ports:
      - 5299:5299
    volumes:
      - /media/server/External/appdata/lazylibrarian:/config
      - complete_downloads:/downloads
      - books:/books
    restart:
      always
    environment:
      - TZ=America/New_York
      - PUID=${PUID}
      - PGID=${PGID}
  #watchtower - docker image updater
  watchtower:
    container_name: watchtower
    restart: always
    image: v2tec/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
#    command: --schedule "0 0 4 * * *" --cleanup
  #netdata - metrics for apps
  netdata:
    image: netdata/netdata
    ports:
      - 19999:19999
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
  #ubooquity - manages comics
  ubooquity:
    image: linuxserver/ubooquity
    container_name: ubooquity
    ports:
    - 2202:2202
    - 2203:2203
    volumes:
    - /media/server/External/appdata/ubooquity:/config
    - complete_downloads:/files
    - comics:/comics
    restart:
      always
    environment:
    - PUID=${PUID}
    - PGID=${PGID}
  #mylar - comic download
  mylar:
    image: linuxserver/mylar
    container_name: mylar
    ports:
      - 8090:8090
    volumes:
      - /media/server/External/appdata/mylay:/config
      - complete_downloads:/downloads
      - comics:/comics
    environment:
    - PUID=${PUID}
    - PGID=${PGID}
    - TZ=America/New_York
  headphones:
    image: linuxserver/headphones
    container_name: headphones
    ports:
    - 8182:8181
    volumes:
    - /media/server/External/appdata/headphones:/config
    - complete_downloads:/downloads
    - music:/music
    environment:
    - PUID=${PUID}
    - PGID=${PGID}
    - TZ=America/New_York
  couchpotato:
    image: linuxserver/couchpotato
    container_name: couchpotato
    ports:
    - 5050:5050
    volumes:
    - /media/server/External/appdata/couchpotato:/config
    - complete_downloads:/downloads
    - movies:/movies
    environment:
    - PUID=${PUID}
    - PGID=${PGID}
    - TZ=America/New_York




volumes:
  comics:
    driver_opts:
      type: none
      device: /media/server/External/comics
      o: bind
  tv:
    driver_opts:
      type: none
      device: /media/server/External/tv
      o: bind
  home_movies:
    driver_opts:
      type: none
      device: /media/server/External/homemovies
      o: bind
  photos:
    driver_opts:
      type: none
      device: /media/server/External/photos
      o: bind
  movies:
    driver_opts:
      type: none
      device: /media/server/External/movies
      o: bind
  kids_movies:
    driver_opts:
      type: none
      device: /media/server/External/kids
      o: bind
  christmas_movies:
    driver_opts:
      type: none
      device: /media/server/External/christmas
      o: bind
  music:
    driver_opts:
      type: none
      device: /media/server/External/music
      o: bind
  books:
    driver_opts:
      type: none
      device: /media/server/External/books
      o: bind
  complete_downloads:
    driver_opts:
      type: none
      device: /media/server/External/complete
      o: bind
  incomplete_downloads:
    driver_opts:
      type: none
      device: /media/server/External/incomplete
      o: bind
  temp_storage:
    driver_opts:
      type: none
      device: /media/server/External/tmp
      o: bind

      
#/media/server/External/appdata/heimdall/config:/config
#/media/server/External/appdata/hydra/config:/config
#/media/server/External/appdata/sabnzbd/config:/config
#/media/server/External/appdata/plex:/config
#/media/server/External/appdata/plexpy:/config
#/media/server/External/appdata/plex/Library/Application\ Support/Plex\ Media\ Server/Logs:/logs:ro
#/media/server/External/appdata/sonarr:/config
#/media/server/External/appdata/letsencrypt:/config
#/media/server/External/appdata/portainer:/data
#/media/server/External/appdata/lazylibrarian:/config
#/media/server/External/appdata/ubooquity:/config
#/media/server/External/appdata/autosub:/config
  

